[2025-07-08T16:08:28.467+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-08T16:08:28.514+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_exercises.process_exercises manual__2025-07-08T16:08:23.566001+00:00 [queued]>
[2025-07-08T16:08:28.526+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_exercises.process_exercises manual__2025-07-08T16:08:23.566001+00:00 [queued]>
[2025-07-08T16:08:28.527+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 1
[2025-07-08T16:08:28.759+0000] {taskinstance.py:2907} INFO - Executing <Task(SparkSubmitOperator): process_exercises> on 2025-07-08 16:08:23.566001+00:00
[2025-07-08T16:08:28.782+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5862) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-08T16:08:28.786+0000] {standard_task_runner.py:72} INFO - Started process 5863 to run task
[2025-07-08T16:08:28.782+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'process_exercises', 'process_exercises', 'manual__2025-07-08T16:08:23.566001+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/process_exercises.py', '--cfg-path', '/tmp/tmpp7z_f9ay']
[2025-07-08T16:08:28.789+0000] {standard_task_runner.py:105} INFO - Job 152: Subtask process_exercises
[2025-07-08T16:08:29.015+0000] {task_command.py:467} INFO - Running <TaskInstance: process_exercises.process_exercises manual__2025-07-08T16:08:23.566001+00:00 [running]> on host 3748f1b8240a
[2025-07-08T16:08:29.408+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='process_exercises' AIRFLOW_CTX_TASK_ID='process_exercises' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T16:08:23.566001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-08T16:08:23.566001+00:00'
[2025-07-08T16:08:29.410+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-07-08T16:08:29.453+0000] {base.py:84} INFO - Retrieving connection 'spark-ebsim'
[2025-07-08T16:08:29.462+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.8.1.jar,/opt/bitnami/spark/jars/nessie-spark-extensions-3.5_2.12-0.103.2.jar,/opt/bitnami/spark/jars/nessie-client-0.103.2.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar, --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/process_exercises_job.py {"id": "CA-SUL-virtual-17RCMe-2025-07-08", "manifest_entry": {"data": {"createdAt": "2025-07-08T16:07:52.045Z", "origin": "CA-SUL", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08"}, "id": "CA-SUL-virtual-17RCMe-2025-07-08"}, "metadata": {"createdAt": "2025-07-08T16:07:52.045Z", "description": "17RCMec", "documents": [{"description": "", "id": "1751990882540", "mimetype": "application/pdf", "name": "Op Jacui IV - Anexo A - Inteligencia.pdf", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/documents/Op Jacui IV - Anexo A - Inteligencia.pdf", "size": 47523, "uploadedAt": "2025-07-08T16:08:02.540Z"}], "endDate": "2025-07-09", "id": "CA-SUL-virtual-17RCMe-2025-07-08", "name": "Exerc\u00edcio Virtual", "origin": "CA-SUL", "simulationType": "virtual", "simulations": [{"id": "172.19.0.14_2025-07-08", "movedAt": "2025-07-08T16:08:10.793Z", "name": "172.19.0.14_2025-07-08", "originalPath": "staging/172.19.0.14_2025-07-08", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/simulations/172.19.0.14_2025-07-08"}], "startDate": "2025-07-08", "trainedForce": "17 Regimento de Cavalaria Mecanizado", "updatedAt": "2025-07-08T16:08:10.794Z", "wikiUrl": ""}}
[2025-07-08T16:08:32.921+0000] {spark_submit.py:644} INFO - 25/07/08 16:08:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-07-08T16:08:34.762+0000] {spark_submit.py:644} INFO - Traceback (most recent call last):
[2025-07-08T16:08:34.762+0000] {spark_submit.py:644} INFO - File "/opt/bitnami/spark/jobs/process_exercises_job.py", line 30, in <module>
[2025-07-08T16:08:34.765+0000] {spark_submit.py:644} INFO - extract_pdf_udf = udf(extract_pdf_text, StringType())
[2025-07-08T16:08:34.765+0000] {spark_submit.py:644} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-07-08T16:08:34.766+0000] {spark_submit.py:644} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 174, in wrapped
[2025-07-08T16:08:34.766+0000] {spark_submit.py:644} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/functions.py", line 15767, in udf
[2025-07-08T16:08:34.766+0000] {spark_submit.py:644} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/udf.py", line 149, in _create_py_udf
[2025-07-08T16:08:34.767+0000] {spark_submit.py:644} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/udf.py", line 81, in _create_udf
[2025-07-08T16:08:34.767+0000] {spark_submit.py:644} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/udf.py", line 174, in __init__
[2025-07-08T16:08:34.768+0000] {spark_submit.py:644} INFO - pyspark.errors.exceptions.base.PySparkTypeError: [NOT_CALLABLE] Argument `func` should be a callable, got module.
[2025-07-08T16:08:34.816+0000] {spark_submit.py:644} INFO - 25/07/08 16:08:34 INFO ShutdownHookManager: Shutdown hook called
[2025-07-08T16:08:34.816+0000] {spark_submit.py:644} INFO - 25/07/08 16:08:34 INFO ShutdownHookManager: Deleting directory /tmp/spark-c195b555-0210-4c31-b9dd-734f76f40efe
[2025-07-08T16:08:34.882+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.8.1.jar,/opt/bitnami/spark/jars/nessie-spark-extensions-3.5_2.12-0.103.2.jar,/opt/bitnami/spark/jars/nessie-client-0.103.2.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar, --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/process_exercises_job.py {"id": "CA-SUL-virtual-17RCMe-2025-07-08", "manifest_entry": {"data": {"createdAt": "2025-07-08T16:07:52.045Z", "origin": "CA-SUL", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08"}, "id": "CA-SUL-virtual-17RCMe-2025-07-08"}, "metadata": {"createdAt": "2025-07-08T16:07:52.045Z", "description": "17RCMec", "documents": [{"description": "", "id": "1751990882540", "mimetype": "application/pdf", "name": "Op Jacui IV - Anexo A - Inteligencia.pdf", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/documents/Op Jacui IV - Anexo A - Inteligencia.pdf", "size": 47523, "uploadedAt": "2025-07-08T16:08:02.540Z"}], "endDate": "2025-07-09", "id": "CA-SUL-virtual-17RCMe-2025-07-08", "name": "Exerc\u00edcio Virtual", "origin": "CA-SUL", "simulationType": "virtual", "simulations": [{"id": "172.19.0.14_2025-07-08", "movedAt": "2025-07-08T16:08:10.793Z", "name": "172.19.0.14_2025-07-08", "originalPath": "staging/172.19.0.14_2025-07-08", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/simulations/172.19.0.14_2025-07-08"}], "startDate": "2025-07-08", "trainedForce": "17 Regimento de Cavalaria Mecanizado", "updatedAt": "2025-07-08T16:08:10.794Z", "wikiUrl": ""}}. Error code is: 1.
[2025-07-08T16:08:34.984+0000] {taskinstance.py:1242} INFO - Marking task as FAILED. dag_id=process_exercises, task_id=process_exercises, run_id=manual__2025-07-08T16:08:23.566001+00:00, execution_date=20250708T160823, start_date=20250708T160828, end_date=20250708T160834
[2025-07-08T16:08:35.139+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-07-08T16:08:35.140+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 152 for task process_exercises (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.8.1.jar,/opt/bitnami/spark/jars/nessie-spark-extensions-3.5_2.12-0.103.2.jar,/opt/bitnami/spark/jars/nessie-client-0.103.2.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar, --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/process_exercises_job.py {"id": "CA-SUL-virtual-17RCMe-2025-07-08", "manifest_entry": {"data": {"createdAt": "2025-07-08T16:07:52.045Z", "origin": "CA-SUL", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08"}, "id": "CA-SUL-virtual-17RCMe-2025-07-08"}, "metadata": {"createdAt": "2025-07-08T16:07:52.045Z", "description": "17RCMec", "documents": [{"description": "", "id": "1751990882540", "mimetype": "application/pdf", "name": "Op Jacui IV - Anexo A - Inteligencia.pdf", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/documents/Op Jacui IV - Anexo A - Inteligencia.pdf", "size": 47523, "uploadedAt": "2025-07-08T16:08:02.540Z"}], "endDate": "2025-07-09", "id": "CA-SUL-virtual-17RCMe-2025-07-08", "name": "Exerc\u00edcio Virtual", "origin": "CA-SUL", "simulationType": "virtual", "simulations": [{"id": "172.19.0.14_2025-07-08", "movedAt": "2025-07-08T16:08:10.793Z", "name": "172.19.0.14_2025-07-08", "originalPath": "staging/172.19.0.14_2025-07-08", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/simulations/172.19.0.14_2025-07-08"}], "startDate": "2025-07-08", "trainedForce": "17 Regimento de Cavalaria Mecanizado", "updatedAt": "2025-07-08T16:08:10.794Z", "wikiUrl": ""}}. Error code is: 1.; 5863)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/bitnami/spark/jars/iceberg-spark-runtime-3.5_2.12-1.8.1.jar,/opt/bitnami/spark/jars/nessie-spark-extensions-3.5_2.12-0.103.2.jar,/opt/bitnami/spark/jars/nessie-client-0.103.2.jar,/opt/bitnami/spark/jars/hadoop-aws-3.3.2.jar,/opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.262.jar, --name arrow-spark --deploy-mode client /opt/bitnami/spark/jobs/process_exercises_job.py {"id": "CA-SUL-virtual-17RCMe-2025-07-08", "manifest_entry": {"data": {"createdAt": "2025-07-08T16:07:52.045Z", "origin": "CA-SUL", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08"}, "id": "CA-SUL-virtual-17RCMe-2025-07-08"}, "metadata": {"createdAt": "2025-07-08T16:07:52.045Z", "description": "17RCMec", "documents": [{"description": "", "id": "1751990882540", "mimetype": "application/pdf", "name": "Op Jacui IV - Anexo A - Inteligencia.pdf", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/documents/Op Jacui IV - Anexo A - Inteligencia.pdf", "size": 47523, "uploadedAt": "2025-07-08T16:08:02.540Z"}], "endDate": "2025-07-09", "id": "CA-SUL-virtual-17RCMe-2025-07-08", "name": "Exerc\u00edcio Virtual", "origin": "CA-SUL", "simulationType": "virtual", "simulations": [{"id": "172.19.0.14_2025-07-08", "movedAt": "2025-07-08T16:08:10.793Z", "name": "172.19.0.14_2025-07-08", "originalPath": "staging/172.19.0.14_2025-07-08", "path": "exercises/CA-SUL-virtual-17RCMe-2025-07-08/simulations/172.19.0.14_2025-07-08"}], "startDate": "2025-07-08", "trainedForce": "17 Regimento de Cavalaria Mecanizado", "updatedAt": "2025-07-08T16:08:10.794Z", "wikiUrl": ""}}. Error code is: 1.
[2025-07-08T16:08:35.153+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-08T16:08:35.189+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-08T16:08:35.216+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
